# Generated by Django 5.1.3 on 2025-01-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.TextField(default='No amenities listed'),
            preserve_default=False,
        ),
    ]
